/**
 * Action Types.
 * @author Ganesh Khutwad.
 */

export const LOAD_CURRENCY_CONVERSION_SUCCESS =
    'LOAD_CURRENCY_CONVERSION_SUCCESS';
export const LOAD_CURRENCY_CONVERSION_FAILED =
    'LOAD_CURRENCY_CONVERSION_FAILED';
export const CURRENCY_CONVERSION_INPROCESS = 'CURRENCY_CONVERSION_INPROCESS';
